#!/bin/bash

cp -u ../home/.bash_aliases ~/
cp -u ../home/.bash_logout ~/
cp -u ../home/.bash_profile ~/
cp -u ../home/.bashrc ~/
cp -ur ../home/.emacs.d/ ~/
cp -u ../home/.gitconfig ~/
cp -ur ../home/.ssh/ ~/
