#!/bin/bash

cp -u ../home/.bash_aliases ~/
cp -u ../home/.bash_logout ~/
cp -u ../home/.bash_profile ~/
cp -u ../home/.bashrc ~/
cp -ur ../home/.emacs.d/ ~/
cp -u ../home/.gitconfig ~/
cp -ur ../home/.ssh/ ~/

source ${HOME}/.bash_aliases
source ${HOME}/.bash_logout
source ${HOME}/.bash_profile
source ${HOME}/.bashrc
